# Generated by Django 4.2.21 on 2025-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FamilyRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_id",
                    models.IntegerField(help_text="Evennia character object ID"),
                ),
                (
                    "related_character_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Evennia character object ID if this is a PC",
                        null=True,
                    ),
                ),
                (
                    "related_character_name",
                    models.CharField(
                        blank=True,
                        help_text="Character name if this is an NPC",
                        max_length=100,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("grandparent", "Grandparent"),
                            ("great_grandparent", "Great-Grandparent"),
                            ("sibling", "Sibling"),
                            ("aunt_uncle", "Aunt/Uncle"),
                            ("niece_nephew", "Niece/Nephew"),
                            ("cousin", "Cousin"),
                            ("second_cousin", "Second Cousin"),
                            ("distant_cousin", "Distant Cousin"),
                            ("child", "Child"),
                            ("grandchild", "Grandchild"),
                            ("great_grandchild", "Great-Grandchild"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["relationship_type", "related_character_name"],
                "unique_together": {
                    (
                        "character_id",
                        "related_character_id",
                        "related_character_name",
                        "relationship_type",
                    )
                },
            },
        ),
    ]
