# Generated by Django 4.2.21 on 2025-10-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("grandparent", "Grandparent"),
                    ("great_grandparent", "Great-Grandparent"),
                    ("sibling", "Sibling"),
                    ("aunt_uncle", "Aunt/Uncle"),
                    ("grand_aunt_uncle", "Grand-Aunt/Uncle"),
                    ("niece_nephew", "Niece/Nephew"),
                    ("grand_niece_nephew", "Grand-Niece/Nephew"),
                    ("cousin", "Cousin"),
                    ("second_cousin", "Second Cousin"),
                    ("distant_cousin", "Distant Cousin"),
                    ("child", "Child"),
                    ("grandchild", "Grandchild"),
                    ("great_grandchild", "Great-Grandchild"),
                    ("parent_in_law", "Parent-in-Law"),
                    ("child_in_law", "Child-in-Law"),
                    ("sibling_in_law", "Sibling-in-Law"),
                ],
                max_length=50,
            ),
        ),
    ]
