# Generated by Django 4.2.21 on 2025-10-23 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("objects", "__first__"),
        ("scripts", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("organisation", "Organisation"),
                            ("event", "Event"),
                            ("public", "Public"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("auto_closed", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "db_typeclass_path__iexact": "typeclasses.story.StoryElement"
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_logs",
                        to="scripts.scriptdb",
                    ),
                ),
                (
                    "organisations",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={
                            "db_typeclass_path__iexact": "typeclasses.organisations.Organisation"
                        },
                        related_name="organisation_scene_logs",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "plots",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={
                            "db_typeclass_path__iexact": "typeclasses.story.StoryElement"
                        },
                        related_name="plot_scene_logs",
                        to="scripts.scriptdb",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "db_typeclass_path__iexact": "typeclasses.rooms.Room"
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_logs",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_logs_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SceneParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_joined_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_left_at", models.DateTimeField(blank=True, null=True)),
                ("is_present", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_participations",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="scenes.scenelog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SceneParticipantSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField()),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="scenes.sceneparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="SceneEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("emit", "Emit"),
                            ("say", "Say"),
                            ("pose", "Pose"),
                            ("roll", "Roll"),
                            ("whisper", "Whisper"),
                            ("arrival", "Arrival"),
                            ("depart", "Depart"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("text", models.TextField()),
                ("text_plain", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_entries",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="scenes.scenelog",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_whispers",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["scene", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="sceneparticipant",
            index=models.Index(
                fields=["scene", "account"], name="scenes_scen_scene_i_a65fe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sceneparticipant",
            index=models.Index(
                fields=["scene", "character"], name="scenes_scen_scene_i_1dc5e6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sceneparticipant",
            unique_together={("scene", "character")},
        ),
        migrations.AddIndex(
            model_name="sceneentry",
            index=models.Index(
                fields=["scene", "sequence"], name="scenes_scen_scene_i_7610f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sceneentry",
            index=models.Index(
                fields=["scene", "entry_type"], name="scenes_scen_scene_i_9813e0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sceneentry",
            unique_together={("scene", "sequence")},
        ),
    ]
