# Generated by Django 4.2.21 on 2025-07-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldinfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldinfopage",
            name="emblem_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional emblem/heraldry image that appears in the upper right of the article",
                null=True,
                upload_to="worldinfo/emblems/",
            ),
        ),
    ]
