# Generated by Django 4.2.21 on 2025-10-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldinfo", "0002_worldinfopage_emblem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    models.TextField(
                        help_text="Main content of the news item. HTML is allowed."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("story", "Story Update"), ("game", "Game News")],
                        default="game",
                        max_length=10,
                    ),
                ),
                (
                    "posted_date",
                    models.CharField(
                        help_text="e.g., 'September 2025' or 'October 13, 2025'",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active news items are shown on the homepage",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers appear first within each category",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["category", "order", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="worldinfopage",
            options={
                "ordering": ["category", "subcategory", "title"],
                "verbose_name": "World Info Page",
                "verbose_name_plural": "World Info Pages",
            },
        ),
        migrations.CreateModel(
            name="MapLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the map this location belongs to",
                        max_length=200,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of the location", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description shown in popup"
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("settlement", "Settlement"),
                            ("landmark", "Landmark"),
                            ("polity", "Polity"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("x_coord", models.FloatField(help_text="X coordinate on the map")),
                ("y_coord", models.FloatField(help_text="Y coordinate on the map")),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional URL to link to (e.g., wiki page)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Map Location",
                "verbose_name_plural": "Map Locations",
                "ordering": ["map_name", "name"],
                "indexes": [
                    models.Index(
                        fields=["map_name", "location_type"],
                        name="worldinfo_m_map_nam_6c88dc_idx",
                    )
                ],
            },
        ),
    ]
